services:
  connect-backend:
    build: ./backend
    container_name: connect-backend
    depends_on:
      - redis_docker
      - postgres_docker
      - chromadb_docker
    ports:
      - "8800:8800"

  connect-frontend:
    build: ./frontend
    container_name: connect-frontend
    depends_on:
      - connect-backend
    ports:
     - "3000:3000"

  nginx-docker:
    build: ./nginx
    container_name: ${NGINX_HOST}
    depends_on:
      - connect-backend
      - connect-frontend
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

  redis_docker:
    image: redis
    container_name: connect_redis
    ports:
      - "6379:6379"

  chromadb_docker:
    image: chromadb/chroma
    container_name: connect-chromadb
    volumes:
      - ./backend/chroma-data:/chroma/chroma
    ports:
      - "8000:8000"

  postgres_docker:
    image: postgres
    container_name: connect-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
